version: '3.3'

services:
  minio01:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - C:\data:/data
    environment:
      - MINIO_ROOT_USER=minio99
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
