version: '3.3'

services:
  minio01:
    image: quay.io/minio/minio
    ports:
      - '9001:9001'
      - '9002:9002'
    volumes:
      - G:\_ehsan\docker-minio\data2:/data
    environment:
      - MINIO_ROOT_USER=admin99
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9002" --address ":9001"
    networks:
      - net1

  minio02:
    image: quay.io/minio/minio
    ports:
      - '9003:9003'
      - '9004:9004'
    volumes:
      - G:\_ehsan\docker-minio\data:/data
    environment:
      - MINIO_ROOT_USER=admin99
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9004" --address ":9003"
    networks:
      - net1

  minio03:
    image: quay.io/minio/minio
    ports:
      - '9005:9005'
      - '9006:9006'
    volumes:
      - G:\_ehsan\docker-minio\data4:/data
    environment:
      - MINIO_ROOT_USER=admin99
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data --console-address ":9006" --address ":9005"
    networks:
      - net1

networks:
  net1:
